export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  LOGIN_VERIFICATION: "/login-verification",
  DASHBOARD: "/dashboard",
  GET_PROFILE: "/get-my-profile",
  STORE_TOKEN: "/store-token",
  LOGOUT: "/logout",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  RESET_LINK: "/reset-link",
  UNAUTHORIZED: "/unauthorized",
  NOT_FOUND: "*",
  ONBOARDING: "/onboarding",
  WELCOME: "/welcome",
  CREDENTIAL_VERIFICATION: "/verification",
  PROVIDER_DASHBOARD: "/provider-dashboard",
  SUPPORT: "/provider/support",
  POST_LOGIN_REDIRECT: "/post-login-redirect",
  WARNING: "warning",
  PENDING_APPROVAL: "pending-approval",
  SETTINGS: "settings",
  PROVIDER_SETTINGS: "provider/settings",
  ORG_DASHBOARD: "dashboard",
  ORG_TRANSMISSIONS: "transmissions",
  ORG_ORDERS: "orders",
  ORG_PROVIDERS: "providers",
  ORG_TRANSACTIONS: "transactions",
  ORG_MEDICATIONS: "medications",
  ORG_PHARMACIES: "pharmacies",
  ORG_ACTIVITY_LOG: "activity-log",
  ORG_SETTINGS: "settings",
  ORG_ORDER_DETAILS: "order/:id",
  ORG_MEDICATION_DETAILS: "medications/:id",
};

export const STEPPER_FORM = {
  ONBOARDING: "onboarding",
  COMPLETE_VERIFICATION: "complete-verification",
};
