export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  GET_PROFILE: "/get-my-profile",
  STORE_TOKEN: "/store-token",
  LOGOUT: "/logout",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  RESET_LINK: "/reset-link",
  UNAUTHORIZED: "/unauthorized",
  NOT_FOUND: "*",
  ONBOARDING: "/onboarding",
  WELCOME: "/welcome",
  CREDENTIAL_VERIFICATION: "/verification",
  PROVIDER_DASHBOARD: "/provider-dashboard",
};
